@startuml
start

:Inicio del proceso;
:¿Qué desea realizar?;

if (Buscar información de \ndelincuentes?) then (Sí)
    :Ingresar a la pestaña \nbuscar delincuentes;
    :Ingresar texto a buscar;
    :Mostrar resultados filtrados\n en la tabla;
else (No)
    if (Buscar información de\n vehículos?) then (Sí)
        :Ingresar a la pestaña de\nla búsqueda de vehículos;
        :Ingresar texto a buscar;
         :Mostrar resultados filtrados\n en la tabla;
    else (No)
        if (Buscar información de \norganizaciones criminales?) then (Sí)
            :ingresar a la pestaña de\n búsqueda de \norganizaciones criminales;
            :Ingresar texto a buscar;
             :Mostrar resultados filtrados\n en la tabla;
        else (No)
            if (Personalizar filtros \nde búsqueda?) then (Sí)
                :Personalizar los filtros \npara la búsqueda según \npreferencias;
                :Ingresar texto a buscar;
                :Mostrar resultados filtrados\n en la tabla;
            else (No)
                :Acción no \nválida;
            endif
        endif
    endif
endif

stop 
@enduml
