@startuml
start

:Inicio del proceso;
:¿Qué desea realizar?;

if (Visualizar información \ncompleta del delincuente?) then (Sí)
    :Seleccionar al delincuente;
    :Precionar boton "ver todo";
    :Mostrar resultados al usuario;
else (No)
    if (Visualizar un historial\n específico por fecha?) then (Sí)
        :Seleccionar al delincuente;
        :Seleccinar historial delictivo a ver;
        :Mostrar historial al usuario;
        if (Registrar condenas \nasociadas a este historial?) then (Sí)
            :Registrar condenas asociadas\nal historial específico;
            :Actualizar historial delictivo;
        endif
    else (No)
        if (Generar reporte en\n PDF con toda la información\n del delincuente?) then (Sí)
            :Seleccionar al delincuente;
            :Generar archivo PDF completo;
            :Descargar PDF;
        else (No)
            if (Generar reporte en \nPDF solo con el perfil \ndel delincuente?) then (Sí)
               :Seleccionar al delincuente;
                :Generar archivo PDF del perfil;
                :Descargar PDF;
            else (No)
                :Acción no válida;
            endif
        endif
    endif
endif

stop
@enduml
