<?php
return [
    'show_warnings' => false,
    'orientation' => 'portrait',
    'defines' => [
        'DOMPDF_FONT_DIR' => storage_path('fonts/'),
        'DOMPDF_FONT_CACHE' => storage_path('fonts/'),
        'DOMPDF_TEMP_DIR' => storage_path('fonts/'),
        'DOMPDF_CHROOT' => base_path(),
        'DOMPDF_ENABLE_FONT_SUBSETTING' => true,
        'DOMPDF_PDF_BACKEND' => 'CPDF',
        'DOMPDF_DEFAULT_MEDIA_TYPE' => 'screen',
        'DOMPDF_DEFAULT_PAPER_SIZE' => 'a4',
        'DOMPDF_DEFAULT_FONT' => 'serif',
        'DOMPDF_DPI' => 96,
        'DOMPDF_ENABLE_PHP' => false,
        'DOMPDF_ENABLE_REMOTE' => true,
        'DOMPDF_ENABLE_CSS_FLOAT' => false,
        'DOMPDF_ENABLE_JAVASCRIPT' => true,
        'DOMPDF_ENABLE_HTML5PARSER' => true,
        'DOMPDF_ENABLE_FONT_SUBSETTING' => false,
        'DOMPDF_FONT_HEIGHT_RATIO' => 1.1,
        'DOMPDF_ENABLE_AUTOLOAD' => true,
        'DOMPDF_ENABLE_JAVASCRIPT' => true,
        'DOMPDF_ENABLE_FONTSUBSET' => true,
        'DOMPDF_DEBUG_CSS' => false,
        'DOMPDF_DEBUG_KEEP_TEMP' => false,
        'DOMPDF_DEBUG_LAYOUT' => false,
        'DOMPDF_DEBUG_LAYOUT_LINES' => false,
        'DOMPDF_DEBUG_LAYOUT_BLOCKS' => false,
        'DOMPDF_DEBUG_LAYOUT_INLINE' => false,
        'DOMPDF_DEBUG_LAYOUT_PADDINGBOX' => false,
        'DOMPDF_LOG_OUTPUT_FILE' => null,
        'DOMPDF_DEFAULT_MEDIA_TYPE' => 'screen',
        'DOMPDF_DEFAULT_PAPER_SIZE' => 'a4',
        'DOMPDF_DEFAULT_FONT' => 'serif',
        'DOMPDF_DPI' => 96,
        'DOMPDF_ENABLE_PHP' => false,
        'DOMPDF_ENABLE_REMOTE' => true,
        'DOMPDF_TEMP_DIR' => storage_path('fonts/'),
        'DOMPDF_CHROOT' => base_path(),
        'public_path' => base_path('public'),
    ]
];
