@startuml
skinparam packageStyle rectangle
skinparam usecase {
    BackgroundColor #F0F8FF
    BorderColor #4682B4
    FontColor #000080
}

skinparam actor {
    BackgroundColor #FFFACD
    BorderColor #4682B4
    FontColor #8B4513
}

skinparam BackgroundColor #E6E6FA
skinparam BorderColor #8A2BE2

top to bottom direction

left to right direction

actor "Usuario\n(Administrador/\nInvestigador/Invitado)" as User

rectangle "Búsqueda" {
    usecase "Buscar información de delincuentes\ncon filtros (generales)" as UC1
    usecase "Buscar información de vehículos\npor datos como marca, modelo, etc." as UC2
    usecase "Buscar información de organizaciones\ncriminales por nombre, tipo, etc." as UC3
    usecase "Personalizar Filtros de Busqueda" as UC9
}

rectangle "Visualización" {
    usecase "Visualizar delincuentes registrados\nen DataTable" as UC6
    usecase "Visualizar vehículos registrados\nen DataTable" as UC4
    usecase "Visualizar organizaciones criminales\nen DataTable" as UC5
}

User --> UC1
User --> UC2
User --> UC3


UC1 --> UC6 : include
UC2 --> UC4 : include
UC3 --> UC5 : include
UC1 --> UC9 : include



@enduml