@startuml
skinparam sequenceArrowColor #4682B4
skinparam actorBorderColor #8B4513
skinparam actorBackgroundColor #FFFACD
skinparam participantBorderColor #4682B4
skinparam participantBackgroundColor #E6E6FA

actor "Usuario" as User
boundary "search_orga" as SearchOrgaView
control "ReportsController" as Controller
entity "criminals" as Criminals #FFD700
entity "arrest_and_apprehension_history" as Arrests #FFA07A
entity "criminal_organizations" as Organizations #98FB98

== Busqueda de Organizaciones criminales ==
User -> SearchOrgaView : Ingresar filtros (nombre, Especialidad, etc)
SearchOrgaView -> Controller : buscarOrganización(filtros)
Controller -> Organizations : consultar(filtros)
Controller -> Criminals : obtenerIntegrantes(organización_id)
Controller -> Arrests : obtenerHistoriales(criminal_ids)
Organizations --> Controller : CoencidenciasEncontradas
Controller --> SearchOrgaView : mostrarResultados()
SearchOrgaView --> User : visualizarInformación()

@enduml
