@startuml
' Estilos visuales
skinparam sequenceArrowColor #4682B4
skinparam actorBorderColor #8B4513
skinparam actorBackgroundColor #FFFACD
skinparam participantBorderColor #4682B4
skinparam participantBackgroundColor #E6E6FA

actor "Usuario" as User
boundary "search_cri" as SearchView
boundary "create_arrest" as ArrestView
control "historialcontroller" as Controller
entity "criminals" as CriminalsDB #FFD700
entity "arrest_and_apprehension_histories" as ArrestDB #FFD700
entity "convictions" as ConvictionsDB #87CEEB

== Búsqueda de delincuentes ==
User -> SearchView : accederVista()
SearchView -> CriminalsDB : obtenerListaDelincuentes()
CriminalsDB -->> SearchView : listaDelincuentes
SearchView --> User : mostrarLista()


User -> SearchView : seleccionarDelincuente()
SearchView -> ArrestView : abrirFormulario("create_arrest")

== Registro de Arresto ==
User -> ArrestView : llenarFormularioArresto()
User -> ArrestView : presionarGuardarArresto()
ArrestView -> Controller : enviarDatosArresto()

Controller --> Controller : validarArresto()

Controller -> ArrestDB : guardarArresto()
ArrestDB -->> Controller : confirmación

Controller --> ArrestView : mostrarMensaje("Arresto agregado con éxito")
ArrestView --> User : mostrarMensaje

== Registro de Condena ==
User -> ArrestView : llenarFormularioCondena()
User -> ArrestView : presionarGuardarCondena()
ArrestView -> Controller : enviarDatosCondena()

Controller --> Controller : validarCondena()

Controller -> ConvictionsDB : guardarCondena()
ConvictionsDB -->> Controller : confirmación

Controller --> ArrestView : mostrarMensaje("Condena agregada con éxito")
ArrestView --> User : mostrarMensaje
@enduml
