@startuml
' Estilo visual y colores
skinparam sequenceArrowColor #4682B4
skinparam actorBorderColor #8B4513
skinparam actorBackgroundColor #FFFACD
skinparam participantBorderColor #4682B4
skinparam participantBackgroundColor #E6E6FA

actor "Usuario" as User

boundary "create_criminal" as CreateView
boundary "search_cri" as SearchView
control "criminalcontroller" as Controller
entity "criminals" as CriminalsDB
entity "physical_characteristics" as CharacteristicsDB
entity "photographs" as PhotographsDB

== Registro completo del delincuente ==

User -> CreateView : abrirFormulario()
CreateView -->> User : formularioCargado

User -> CreateView : llenarFormulario()
User -> CreateView : PrecionarBotonGuardar()

CreateView -> Controller : enviarFormularioCompleto()

Controller --> Controller : validarDatosGenerales()

Controller --> Controller : validarCaracteristicas()

Controller --> Controller : validarFotografias()


alt Todos los datos son válidos
    Controller -> CriminalsDB : guardarDatosGenerales()
    

    Controller -> CharacteristicsDB : guardarCaracteristicas()
  
    Controller -> PhotographsDB : guardarFotografias()
    PhotographsDB -->> Controller : confirmación

    Controller --> SearchView : redirigir("Guardado con éxito")

    SearchView --> User : mostrarVista("Lista de delincuentes")
 
else Algún dato es inválido
    Controller ---> CreateView : mostrarErrores("Errores de validación")

    CreateView --> User : notificar("Revisar datos ingresados")
   
end

@enduml
