@startuml
skinparam sequenceArrowColor #4682B4
skinparam actorBorderColor #8B4513
skinparam actorBackgroundColor #FFFACD
skinparam participantBorderColor #4682B4
skinparam participantBackgroundColor #E6E6FA

actor "Usuario" as User
boundary "search_cri" as SearchView
control "ReportsController" as Controller
entity "criminals" as Criminals #FFD700
entity "arrest_and_apprehension_history" as Arrests #FFA07A
boundary "show_file_history" as HistoryView

== Visualización del perfil + historial del delincuente ==
User -> SearchView : buscarDelincuente(filtros)
SearchView -> Controller : seleccionarDelincuente(criminal_id)
Controller -> Criminals : obtenerInformacion(criminal_id)
Controller -> Arrests : obtenerHistoriales(criminal_id)
Controller -> HistoryView : mostrarPerfilYHistorial()
HistoryView --> User : visualizarInformación()

@enduml
